/* Track B — runtime-owned process entry (doc-2 §2.9).
 *
 * A NEW archive member holding the runtime's own main(). It ships TODAY, ahead
 * of Track A's A-M5 flip, and is inert until then. The reason it is safe:
 * an object file's own main() is a STRONG definition on the linker command
 * line, and a static archive member is pulled ONLY to resolve an *undefined*
 * symbol. So whenever the linked object already defines main() — as every
 * program LlvmGen emits does today, and as runtime/selftest.c does — the
 * linker never reaches into the archive for main() and this member stays
 * unpulled (proven both ways in doc-2 §10's B-M4 entry).
 *
 * Once A-M5 flips LlvmGen to emit lv_main() instead of its own main(), the
 * generated object leaves main() undefined, the linker pulls THIS member to
 * satisfy it, and lv_main() (defined by that same generated object) resolves
 * the call below. No driver or CMake change is needed at that point.
 *
 * Every line here goes through the runtime's own entry/loop API declared in
 * lv_abi.h — no platform primitive is touched directly, so the platform-floor
 * audit covers this file too.
 */
#include "lv_abi.h"
#include "lv_task.h"   /* LA-30 doc 2 §5: the scheduler carries the program lifetime */

/* Generated by Track A at A-M5; not part of the ABI header (generated
 * code never calls it — the runtime calls into it). */
extern void lv_main(LvValue* ret);

/* Task-0 thunk (LA-30 doc 2 §5): lv_main under the lv_task_fn signature. */
static void lv_main_task(void* a, void* b) {
    (void)b;
    lv_main((LvValue*)a);
}

#if defined(__wasm__)
/* Track W (doc 02 §6/§7, hard-02's link lane): on native, `main` (the entry
 * symbol lv_entry.c exposes) is pulled from the archive automatically —
 * every generated object leaves it undefined, so the linker always needs it.
 * wasm-ld's archive pulls are the same "someone must need this symbol"
 * mechanism, but nothing needs `lv_entry_main` that way (no crt0, no libc
 * `_start` — main.cpp's link lane skips both), so it has to be forced with
 * `--export=lv_entry_main`; `export_name` then pins the WASM EXPORT table
 * entry to "main" regardless of that internal C name, so the JS host
 * (lv_host.js) and any `--invoke main` driver still call it by the same name
 * as the doc's `--export=<entry>` describes. A literal `main(argc, argv)` is
 * NOT used as the forced symbol itself: clang mangles a wasm `main` with
 * this signature to `__main_argc_argv` (there being no process argv on this
 * target otherwise), which would make the forcing flag an obscure,
 * signature-dependent implementation detail instead of a name this file
 * controls directly. */
__attribute__((export_name("main")))
int lv_entry_main(int argc, char** argv) {
#else
int main(int argc, char** argv) {
#endif
    lv_rt_init(argc, argv);            /* regions, registries, argv capture */

    LvValue ret;
    if (lv_tasks_enabled()) {
        /* LA-30 (doc 2 §5): lv_main runs as task 0; awaits park instead of
         * pumping; the scheduler drains the loop (its loop_step hook spawns
         * every user callback as a task) until the thread quiesces. */
        lv_sched_init();
        lv_sched_hooks(lvrt_promise_state, lvrt_loop_step_tasks);
        lv_sched_throw_probe(lvrt_throwing);          /* G11 probe = gThrowing read */
        lv_sched_run(lv_main_task, &ret, NULL);
        /* Cross-task uncaught (doc 2 §8): the scheduler exited its throw gate
         * while task 0 was still parked, so lv_main's own uncaught/meter tail
         * never ran — report here (sets exit code 1). When task 0 DID complete,
         * its emitted tail already called lvrt_uncaught; calling again would
         * double-report, hence the completion probe. */
        if (lvrt_throwing() && !lv_sched_main_completed())
            lvrt_uncaught();
    } else {
        lv_main(&ret);                 /* run the program's top-level body */

        /* Drain remaining live work — due timers, fd watches, pending promises —
         * via the same two entry points Await's codegen pumps (§2.9). Verbatim
         * today's shape; deleted at M6 with the rest of the pump. */
        while (lvrt_loop_has_work())
            lvrt_loop_step();
    }

    /* Guaranteed restore-on-exit (designs/terminal-raw-mode.md §3.4): if the
     * program entered raw mode and never restored, put the terminal back before
     * the process returns. No-op otherwise. Peer of the uncaught/lv_die sites.
     * Stays OUTSIDE the scheduler (doc 2 §5): it must run even when the
     * scheduler exits via the drain or throw-gate paths. */
    lvrt_term_shutdown();

    return lv_rt_exit_code();
}
