name = "atlantis"
sources = ["src/kernel/*.lev", "src/log/*.lev", "src/routing/*.lev", "src/json/*.lev", "src/config/*.lev", "src/app/*.lev", "src/di/*.lev", "src/data/*.lev", "src/orm/*.lev", "src/mcp/*.lev", "src/openapi/*.lev", "src/client/*.lev", "src/auth/*.lev"]
version = "0.1.0"
