cmake_minimum_required(VERSION 3.20)  # CMP0057 NEW: IN_LIST operator in if()

# Generates build/generated/PreludeEmbedded.cpp from prelude/*.lev.
#
# Invoked as a `cmake -P` script from an add_custom_command (CMakeLists.txt).
# Inputs (all -D on the command line):
#   OUT         : output .cpp path
#   PRELUDE_DIR : directory holding the <seg>.lev files
#   SEGMENTS    : comma-list of segment stems, in canonical concatenation order
#   WASM_ONLY   : comma-list of stems that are wasm32*-only
# (comma-joined, not ;-joined: a ;-list would be re-split by the shell before
#  reaching this script; we rejoin on "," below.)
#
# Emits an ordered `kPreludeSegments[]` table matching PreludeSegment
# (src/PreludeEmbedded.hpp): the embedded fallback used by
# Resolver::parsePrelude() when no prelude directory resolves. Bytes are
# emitted as a hex array (delimiter-proof, no host-tool dependency) and are
# byte-identical to the .lev files by construction (design R1).

string(REPLACE "," ";" SEGMENTS "${SEGMENTS}")
string(REPLACE "," ";" WASM_ONLY "${WASM_ONLY}")

set(body "// GENERATED by cmake/GenPreludeEmbedded.cmake — do not edit.\n")
string(APPEND body "#include \"PreludeEmbedded.hpp\"\n\n")

set(table "")
set(count 0)
foreach(seg IN LISTS SEGMENTS)
  set(f "${PRELUDE_DIR}/${seg}.lev")
  if(NOT EXISTS "${f}")
    message(FATAL_ERROR "GenPreludeEmbedded: missing prelude file ${f}")
  endif()
  file(READ "${f}" hex HEX)
  string(LENGTH "${hex}" hexlen)
  math(EXPR nbytes "${hexlen} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(APPEND body "static const unsigned char kSeg_${seg}[] = { ${bytes} };\n")

  set(wasmOnly "false")
  if(seg IN_LIST WASM_ONLY)
    set(wasmOnly "true")
  endif()
  string(APPEND table "    { \"${seg}\", ${wasmOnly}, kSeg_${seg}, ${nbytes}UL },\n")
  math(EXPR count "${count} + 1")
endforeach()

string(APPEND body "\nconst PreludeSegment kPreludeSegments[] = {\n${table}};\n")
string(APPEND body "const unsigned long kPreludeSegmentCount = ${count}UL;\n")

file(WRITE "${OUT}" "${body}")
